### ISSUE TITLE
Windows - cannot load guard/guard

### ISSUE THREAD

**Issue by randohinn** [Voog/voog-kit#44]
Hi, When I try to do a kit pull on Windows 10, this is what happens:

```
C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- guard/guard (LoadError)
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/voog-kit-0.3.9/lib/voog/dtk/guard.rb:2:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/voog-kit-0.3.9/bin/kit:10:in `<top (required)>'
        from C:/Ruby22/bin/kit:23:in `load'
        from C:/Ruby22/bin/kit:23:in `<main>
```
I've tried installing guard gem manually, and updating all of my gems, to no avail...

@mikkpr Might be something to do with your latest commit?

**Comment by mikkpr** [comment]
It most definitely is. I'm currently working on a fix, but can't give you an ETA yet.

**Comment by mikkpr** [comment]
@randohinn The latest release (0.4.0) should solve your issue – I completely rewrote the file watcher and as a result, Guard is no longer a runtime dependency. Please confirm it works for you as well :)
